-- WordPress naming leaves the data model:
-- * imported rows take their WordPress id as their own id (content, URLs like ?member_cat=51 and field
--   values such as image and venue ids refer to them), and the wp_id columns go;
-- * post types and taxonomies get the site's names (src/lib/content/wp-names.ts);
-- * rows of post types WordPress no longer registers are removed.
-- Fields and content are rewritten by re-running the importer.

alter table public.entries disable trigger entries_touch;
alter table public.media disable trigger media_touch;

delete from public.entries where type in ('evl_event', 'guide-days', 'guides', 'evl_partner');

-- Ids can be given explicitly (the importer does); new rows still get the next one.
alter table public.media alter column id set generated by default;
alter table public.entries alter column id set generated by default;
alter table public.terms alter column id set generated by default;

-- Renumber with the foreign keys off: old id -> WordPress id (rows made here, without one, go after the
-- highest). Ids move out of the way first so none is taken twice mid-update.
alter table public.entries drop constraint entries_parent_id_fkey, drop constraint entries_featured_media_id_fkey;
alter table public.revisions drop constraint revisions_entry_id_fkey;
alter table public.terms drop constraint terms_parent_id_fkey;
alter table public.entry_terms drop constraint entry_terms_entry_id_fkey, drop constraint entry_terms_term_id_fkey;

create temporary table media_ids as
  select id as old, coalesce(wp_id, (select max(wp_id) from public.media) + row_number() over (partition by wp_id is null order by id)) as new from public.media;
create temporary table term_ids as
  select id as old, coalesce(wp_id, (select max(wp_id) from public.terms) + row_number() over (partition by wp_id is null order by id)) as new from public.terms;
create temporary table entry_ids as
  select id as old, coalesce(wp_id, (select max(wp_id) from public.entries) + row_number() over (partition by wp_id is null order by id)) as new from public.entries;

update public.media set id = id + 1000000000;
update public.media t set id = m.new from media_ids m where t.id = m.old + 1000000000;
update public.terms set id = id + 1000000000;
update public.terms t set id = m.new from term_ids m where t.id = m.old + 1000000000;
update public.terms t set parent_id = m.new from term_ids m where t.parent_id = m.old;
update public.entries set id = id + 1000000000;
update public.entries t set id = m.new from entry_ids m where t.id = m.old + 1000000000;
update public.entries t set parent_id = m.new from entry_ids m where t.parent_id = m.old;
update public.entries t set featured_media_id = m.new from media_ids m where t.featured_media_id = m.old;
update public.revisions t set entry_id = m.new from entry_ids m where t.entry_id = m.old;
create temporary table links as
  select e.new as entry_id, tm.new as term_id, l.sort from public.entry_terms l join entry_ids e on e.old = l.entry_id join term_ids tm on tm.old = l.term_id;
delete from public.entry_terms;
insert into public.entry_terms (entry_id, term_id, sort) select entry_id, term_id, sort from links;

alter table public.entries
  add constraint entries_parent_id_fkey foreign key (parent_id) references public.entries on delete set null,
  add constraint entries_featured_media_id_fkey foreign key (featured_media_id) references public.media on delete set null;
alter table public.revisions add constraint revisions_entry_id_fkey foreign key (entry_id) references public.entries on delete cascade;
alter table public.terms add constraint terms_parent_id_fkey foreign key (parent_id) references public.terms on delete set null;
alter table public.entry_terms
  add constraint entry_terms_entry_id_fkey foreign key (entry_id) references public.entries on delete cascade,
  add constraint entry_terms_term_id_fkey foreign key (term_id) references public.terms on delete cascade;

alter table public.media drop column wp_id;
alter table public.terms drop column wp_id;
alter table public.entries drop column wp_id;

-- Identities continue after the highest id.
create or replace function public.sync_id_sequences()
returns void
language sql
security definer
set search_path = ''
as $$
  select setval(pg_get_serial_sequence('public.media', 'id'), greatest((select max(id) from public.media), 1));
  select setval(pg_get_serial_sequence('public.terms', 'id'), greatest((select max(id) from public.terms), 1));
  select setval(pg_get_serial_sequence('public.entries', 'id'), greatest((select max(id) from public.entries), 1));
  select setval(pg_get_serial_sequence('public.forms', 'id'), greatest((select max(id) from public.forms), 1));
$$;
revoke execute on function public.sync_id_sequences() from public, anon, authenticated;
drop function public.forms_sync_id_sequence();
select public.sync_id_sequences();

update public.entries set type = case type
  when 'tribe_events' then 'event'
  when 'tribe_venue' then 'venue'
  when 'tribe_organizer' then 'organizer'
  when 'evl_member' then 'member'
  when 'evl_guide' then 'guide'
  when 'evl_experience' then 'experience'
  when 'evl_sponsor' then 'sponsor'
  when 'wp_block' then 'block'
  else type end;
update public.terms set taxonomy = case taxonomy
  when 'tribe_events_cat' then 'event_category'
  when 'evl_season' then 'season'
  when 'post_tag' then 'tag'
  else taxonomy end;

drop index public.entries_event_start_idx;
create index entries_event_start_idx on public.entries (event_start) where type = 'event';

delete from public.settings where key in ('wp_options', 'global_styles_css');
update public.settings set key = 'options' where key = 'acf_options';
update public.settings set value = (value - 'front_page_wp_id') || jsonb_build_object('front_page_id', value->'front_page_wp_id') where key = 'site';

alter table public.entries enable trigger entries_touch;
alter table public.media enable trigger media_touch;

comment on column public.entries.type is 'page, post, event, venue, organizer, member, guide, experience, sponsor, block';
comment on column public.terms.taxonomy is 'category, tag, member_category, content_feed, season, event_category';
