-- Form builder. `definition` is a Gravity Forms form object (fields, button, confirmations, label
-- placement...), so imported forms keep their ids and markup. Notification settings hold email
-- addresses, so they live in their own column that anonymous visitors can't select.

create table public.forms (
  id integer generated by default as identity primary key,
  title text not null,
  definition jsonb not null default '{}'::jsonb,
  notifications jsonb not null default '[]'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger forms_touch before update on public.forms
  for each row execute function public.touch_updated_at();

alter table public.forms enable row level security;

create policy "forms public read" on public.forms for select using (is_active or (select public.is_editor()));
create policy "forms editor write" on public.forms for all to authenticated
  using ((select public.is_editor())) with check ((select public.is_editor()));

revoke select on public.forms from anon;
grant select (id, title, definition, is_active, created_at, updated_at) on public.forms to anon;

alter table public.form_submissions add column form_id integer references public.forms (id) on delete set null;
create index form_submissions_form_id on public.form_submissions (form_id, created_at desc);

create policy "forms editor delete submissions" on public.form_submissions for delete to authenticated
  using ((select public.is_editor()));
